---
- name: Create directory for nginx configuration
  file:
    path: /etc/nginx
    state: directory

- name: Copy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Run nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/www/html:/usr/share/nginx/html
    state: started
    restart_policy: always
